### ISSUE TITLE
getMatchingStatements from Any Graph doesn't work

### ISSUE THREAD

**Issue by white-gecko** [SaftIng/Saft#38]
Calling `getMatchingStatements()` on `Store` with a pattern containing an `AnyPattern` as graph results in an empty result even though all graphs should be taken into account. This issue occurs at least with the Virtuoso back end.

We should further decide whether the `AnyPattern` should match all named graphs including the default graph or excluding the default graph or if we want to provide special patterns to implement one of these cases.

There is not test yet for this bug.

**Comment by k00ni** [comment]
> Calling getMatchingStatements() on Store with a pattern containing an AnyPattern as graph results in an empty result even though all graphs should be taken into account.

I am wondering, how shall we solve the following issue: If you use `AnyPattern` for the graph in the Statement you give to getMatchingStatements and you receive statements from multiple graphs, what value has the graph property of each of these statements?

It is unclear were statements came from, so if `AnyPattern` was used the result statements have null in their graph property, because their source is undefined. 

> We should further decide whether the AnyPattern should match all named graphs including the default graph or excluding the default graph or if we want to provide special patterns to implement one of these cases.

I think we set some standard, and if you want to change that, you can do it by set a $config value. For such cases we have that. 

What you think?

**Comment by white-gecko** [comment]
The returned statements should contain the originating graph.
So it would be translated to something like:

```
select ?s ?p ?o ?g {
 graph ?g {?s ?p ?o}
 filter(?s = <http://example.org/s>)
 filter(?p = <http://example.org/p>)
}
```

resp.

```
select ?o ?g {
 graph ?g {<http://example.org/s> <http://example.org/p> ?o}
}
```

while subject and predicate are added after the query evaluation.
