### ISSUE TITLE
Deal with API inconsistancy in imported libraries 

### ISSUE THREAD

**Issue by white-gecko** [SaftIng/Saft#68]
What do we want to do with imported libraries, which use undescore-namespaces e.g. `EasyRdf_Graph` in the stable release, while the dev-master is using namespaces e.g. `\EasyRdf\Graph`.

How do we want to define the versions of the dependencies in composer for a stable release?

**Comment by k00ni** [comment]
I updated the composer.json so that all libraries, except Erfurt, are defined with fixed major and minor release information. As i understand on semantic versioning right, we don't have to care about the patch position of a version.

When you upgrade Erfurt, can you please add its new version to composer.json?
